### ISSUE TITLE
Cavernous II: Grind info box don't update in real time as other info box.

### ISSUE THREAD

**Issue by talregev** [Nucaranlaeg/Nucaranlaeg.github.io#74]
It will be nice that Grind info box will update after each reset of path automatic that I can follow how much to grind (even without activate the grind):

![image](https://github.com/Nucaranlaeg/Nucaranlaeg.github.io/assets/7043539/a01c4229-74c0-4d67-8c58-96cee0d7648f)

Other info box update on real time:
![image](https://github.com/Nucaranlaeg/Nucaranlaeg.github.io/assets/7043539/0711dee9-8eab-4adc-937c-54955947bd33)

**Comment by Nucaranlaeg** [comment]
This will not make it into Cavernous II, as no future updates are being made for Cavernous II (I may still merge PRs if someone else makes them).  Cavernous III will have this.

**Comment by Nucaranlaeg** [comment]
Yeah, I'll still fix bugs.
